version: '3'

services:
  # backend-meutroco:
  #   build:
  #     context: ./backend
  #   container_name: backend-meutroco
  #   ports:
  #     - '3333:3333'
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres

  postgres:
    image: 'postgres:13-alpine'
    container_name: database-meutroco
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /database/meutroco:/var/lib/postgresql/data
