name: MeuTroco

on:
  push:
    branches: [ develop ]

jobs:
  push-to-dockerhub:
    name: Push to DockerHub
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gustavocolombo/meutroco
          tags: latest

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER }}
          PORT: 22
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd ~
            docker pull gustavocolombo/meutroco:latest
            docker stop MEUTROCO_API
            docker rm MEUTROCO_API
            docker run --network="host" --detach --name MEUTROCO_API gustavocolombo/meutroco:latest
